version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./src/nginx-certs:/etc/nginx/certs
      - ./src/nginx-vhost:/etc/nginx/vhost.d
      - ./src/nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      staging_network:

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
      DEFAULT_EMAIL: "josuedjh456@gmail.com"
    volumes:
      - ./src/nginx-certs:/etc/nginx/certs
      - ./src/nginx-vhost:/etc/nginx/vhost.d
      - ./src/nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      staging_network:

networks:
  staging_network:
   name: dev_staging_net

volumes:
  nginx-proxy:
  nginx-certs:
  nginx-vhost:
  nginx-html:
