version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always

    networks:
      dev_staging:

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./src/nginx-certs:/etc/nginx/certs
      - ./src/nginx-vhost:/etc/nginx/vhost.d
      - ./src/nginx-html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always

    networks:
      dev_staging:

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./src/nginx-certs:/etc/nginx/certs
      - ./src/nginx-vhost:/etc/nginx/vhost.d
      - ./src/nginx-html:/usr/share/nginx/html

    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
      DEFAULT_EMAIL: "hi@labtrendig.com"

  web:
    image: adamkdean/redirect
    expose:
     - 8000
    environment:
      HTTP_PORT: 8000
      VIRTUAL_HOST: www.task.labtrendig.com
      LETSENCRYPT_HOST: www.task.labtrendig.com
      LETSENCRYPT_EMAIL: "hi@labtrendig.com"
    networks:
      dev_staging:

networks:
  dev_staging:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
