- name: Install python if missing
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  register: "command"
  changed_when: "command.stdout != ''"

- name: Install aptitude
  apt:
    name: aptitude
    state: present

- name: Upgrade all packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Set default hostname aliases
  lineinfile: "dest=/etc/hosts line='{{ item.ip }} {{ item.hostname }}' owner=root group=root mode=0644"
  tags: hosts
  with_items:
    - { ip: "127.0.0.1", hostname: "{{ hostname }}" }
    - { ip: "127.0.1.1", hostname: "{{ hostname }}" }

- name: Set hostname
  hostname: "name={{ hostname }}"

- name: Uninstall unwanted packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - snapd
    - accountsservice

- name: Remove unwanted packages
  become: true
  apt: "name={{ item }} state=absent"
  with_items:
    - snapd
    - accountsservice

- include: _tools.yml
  tags:
    - base.tools

- include: _security.yml
  tags:
    - base.segurity

- name: Set useful sysctl settings
  sysctl: "name={{ item.name }} value={{ item.value }} sysctl_set=yes"
  with_items:
    - { name: "fs.file-max", value: "2097152" }
    - { name: "net.core.somaxconn", value: 7600 }

- name: Install unattended upgrades
  apt: name=unattended-upgrades state=present

- name: Install ntp server
  apt: name=ntp state=present

- name: Ensure ntpd is running and enabled
  service: name=ntp state=started enabled=yes
