- name: Add docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu  bionic stable
    state: present
    update_cache: yes

- name: Install docker
  apt: name=docker-ce state=present

- name: Ensure docker service is installed and enabled
  service: name=docker state=started enabled=yes

- name: Ensure docker group exists
  group: name=docker state=present

- name: Add admin to the docker group
  user: name=ubuntu groups=docker append=yes

- name: Install docker-compose
  pip: name=docker-compose